/** Utility functions for the Northstar MCP server. */

/**
 * Convert text to a safe branch name slug.
 *
 * @param text Input text
 * @returns Slugified text suitable for branch names
 */
export function slugify(text: string): string {
  // Convert to lowercase
  let slug = text.toLowerCase();

  // Replace spaces and underscores with hyphens
  slug = slug.replace(/[\s_]+/g, "-");

  // Remove non-alphanumeric characters except hyphens
  slug = slug.replace(/[^a-z0-9-]/g, "");

  // Remove leading/trailing hyphens and collapse multiple hyphens
  slug = slug.replace(/-+/g, "-").replace(/^-|-$/g, "");

  // Truncate to reasonable length (50 chars)
  if (slug.length > 50) {
    slug = slug.substring(0, 50).replace(/-$/, "");
  }

  return slug || "unnamed-branch";
}

/**
 * Generate a unified diff between two strings.
 *
 * @param original Original content
 * @param modified Modified content
 * @param filename Filename to display in diff header
 * @returns Unified diff as a string
 */
export function unifiedDiff(
  original: string,
  modified: string,
  filename: string = "file"
): string {
  const originalLines = original.split(/\r?\n/);
  const modifiedLines = modified.split(/\r?\n/);

  // Simple unified diff implementation
  const diff: string[] = [];
  diff.push(`--- a/${filename}`);
  diff.push(`+++ b/${filename}`);

  // Use a simple algorithm to find differences
  let i = 0;
  let j = 0;
  const maxI = originalLines.length;
  const maxJ = modifiedLines.length;

  while (i < maxI || j < maxJ) {
    if (i >= maxI) {
      // Only modified lines remain
      diff.push(`@@ -${i},0 +${j},${maxJ - j} @@`);
      for (let k = j; k < maxJ; k++) {
        diff.push(`+${modifiedLines[k]}`);
      }
      break;
    } else if (j >= maxJ) {
      // Only original lines remain
      diff.push(`@@ -${i},${maxI - i} +${j},0 @@`);
      for (let k = i; k < maxI; k++) {
        diff.push(`-${originalLines[k]}`);
      }
      break;
    } else if (originalLines[i] === modifiedLines[j]) {
      // Lines match, skip both
      i++;
      j++;
    } else {
      // Find the next matching line or end
      let matchFound = false;
      let nextI = i + 1;
      let nextJ = j + 1;

      // Try to find a match within a window
      for (let window = 1; window <= 10 && !matchFound; window++) {
        if (i + window < maxI && originalLines[i + window] === modifiedLines[j]) {
          // Found a match for original
          diff.push(`@@ -${i},${window} +${j},0 @@`);
          for (let k = i; k < i + window; k++) {
            diff.push(`-${originalLines[k]}`);
          }
          i = i + window;
          matchFound = true;
        } else if (j + window < maxJ && originalLines[i] === modifiedLines[j + window]) {
          // Found a match for modified
          diff.push(`@@ -${i},0 +${j},${window} @@`);
          for (let k = j; k < j + window; k++) {
            diff.push(`+${modifiedLines[k]}`);
          }
          j = j + window;
          matchFound = true;
        }
      }

      if (!matchFound) {
        // Simple case: one line changed
        const startI = i;
        const startJ = j;
        i++;
        j++;
        diff.push(`@@ -${startI + 1},1 +${startJ + 1},1 @@`);
        diff.push(`-${originalLines[startI]}`);
        diff.push(`+${modifiedLines[startJ]}`);
      }
    }
  }

  return diff.join("\n");
}

/**
 * Format the pull request body with instruction, file info, and diff.
 *
 * @param instruction The instruction describing the change
 * @param filePath Path to the modified file
 * @param diff Unified diff of changes
 * @returns Formatted PR body in markdown
 */
export function formatPRBody(
  instruction: string,
  filePath: string,
  diff: string
): string {
  // Truncate diff to 100 lines
  const lines = diff.split("\n");
  let truncatedDiff: string;
  if (lines.length > 100) {
    truncatedDiff = lines.slice(0, 100).join("\n");
    const remaining = lines.length - 100;
    truncatedDiff += `\n\n... (${remaining} more lines truncated)`;
  } else {
    truncatedDiff = diff;
  }

  const body = `## Instruction

${instruction}

## Modified File

\`${filePath}\`

## Changes

\`\`\`diff
${truncatedDiff}
\`\`\`

---
Generated by Northstar AI Agent using Morph Fast Apply
`;

  return body;
}

