"""Utility functions for the Northstar MCP server."""

import re
import difflib
from pathlib import Path
from typing import Optional


def slugify(text: str) -> str:
    """
    Convert text to a safe branch name slug.

    Args:
        text: Input text

    Returns:
        Slugified text suitable for branch names
    """
    # Convert to lowercase
    text = text.lower()

    # Replace spaces and underscores with hyphens
    text = re.sub(r'[\s_]+', '-', text)

    # Remove non-alphanumeric characters except hyphens
    text = re.sub(r'[^a-z0-9-]', '', text)

    # Remove leading/trailing hyphens and collapse multiple hyphens
    text = re.sub(r'-+', '-', text).strip('-')

    # Truncate to reasonable length (50 chars)
    if len(text) > 50:
        text = text[:50].rstrip('-')

    return text or 'unnamed-branch'


def unified_diff(original: str, modified: str, filename: str = "file") -> str:
    """
    Generate a unified diff between two strings.

    Args:
        original: Original content
        modified: Modified content
        filename: Filename to display in diff header

    Returns:
        Unified diff as a string
    """
    original_lines = original.splitlines(keepends=True)
    modified_lines = modified.splitlines(keepends=True)

    diff = difflib.unified_diff(
        original_lines,
        modified_lines,
        fromfile=f"a/{filename}",
        tofile=f"b/{filename}",
        lineterm=''
    )

    return ''.join(diff)


def format_pr_body(instruction: str, file_path: str, diff: str) -> str:
    """
    Format the pull request body with instruction, file info, and diff.

    Args:
        instruction: The instruction describing the change
        file_path: Path to the modified file
        diff: Unified diff of changes

    Returns:
        Formatted PR body in markdown
    """
    # Truncate diff to 100 lines
    lines = diff.splitlines()
    if len(lines) > 100:
        truncated_diff = '\n'.join(lines[:100])
        remaining = len(lines) - 100
        truncated_diff += f"\n\n... ({remaining} more lines truncated)"
    else:
        truncated_diff = diff

    body = f"""## Instruction

{instruction}

## Modified File

`{file_path}`

## Changes

```diff
{truncated_diff}
```

---
Generated by Northstar AI Agent using Morph Fast Apply
"""

    return body
